name: lets_train
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0


workspace:
  # Apps
  - app

  # # Packages
  - packages/ui_kit
  # - packages/database
  # - packages/calendar
  # - packages/workout

  # - packages/inset_shadows