name: lets_train
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.3.2
  hooks_riverpod: ^3.3.2
  riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.4


workspace:
  # Apps
  - app

  # # Packages
  - packages/ui_kit
  # - packages/database
  # - packages/calendar
  # - packages/workout

  # - packages/inset_shadows